imports:
  - logging.yaml
  - model.yaml
  - training.yaml
  - dataset_monai.yaml
  - runner.yaml

environment:
  seed: 42
  device: "cuda"

experiment:
  name: "recurrance_dmodel_256_lr1e5"
  work_dir: "work_dirs/experiments/recurrance_dmodel_256_lr1e5"
  tags:
    - "baseline"
    - "clinical_label"
  description: "Baseline model for breast MRI molecular subtype classification"
