imports:
  - logging.yaml
  - model.yaml
  - training.yaml
  - dataset.yaml

# You can override specific settings here if needed
environment:
  seed: 42
  device: "cuda"
  num_workers: 4
  pin_memory: true

experiment:
  name: "breast_mri_classification"
  tags:
    - "baseline"
    - "molecular_subtype"
  description: "Baseline model for breast MRI molecular subtype classification"
