dataset:
  name: "bmri_dataset"
  params:
    root_dir: "data/Duke-Breast-Cancer-MRI"
    clinical_data_path: "data/Clinical_and_Other_Features.xlsx"
    clinical_features_columns:
      - ['MRI Technical Information', 'Columns', '320=0,448=1,512=2']
      - ['Tumor Characteristics', 'Staging(Metastasis)#(Mx -replaced by -1)[M]', '']
      - ['MRI Findings', 'Lymphadenopathy or Suspicious Nodes', '{0 = no, 1 = yes}']

  indices:
    train: [358]
    # train: [2, 8, 18, 20, 47, 48, 53, 57, 59, 61, 64, 91, 92, 102, 117, 137, 145, 153, 154, 162, 180, 185, 196, 208, 221, 222, 227, 233, 243, 246, 251, 255, 257, 284, 286, 295, 311, 316, 318, 322, 329, 340, 348, 351, 352, 354, 355, 359, 375, 383, 415, 419, 423, 424, 425, 434, 435, 438, 444, 446, 456, 462, 483, 492, 516, 534, 550, 552, 555, 561, 565, 571, 579, 590, 612]
    # val: [1, 709, 722, 731, 741, 755, 776, 780, 795, 810, 821, 828, 831, 861, 873, 876, 886, 906, 921, 639, 657, 658, 662, 664, 677, 694]
    # test: [14, 26, 187, 197, 231, 288, 350, 386, 389, 453, 490, 503, 515, 595, 598, 628, 629, 708, 711, 751, 806, 815, 820, 825, 827, 842, 849]

  transforms:
    target_size: &target_size [144, 144, 96]
    train:
      - name: "MRITorchIOPipeline"
        params:
          transforms_config:
            - name: "Resize"
              params:
                target_shape: *target_size

            - name: "RandomBiasField"

            - name: "RandomMotion"
              params:
                degrees: 5
                translation: 5
                num_transforms: 2

            - name: "RandomNoise"
              params:
                meas: 9
                std: [0.1, 0.5]

            - name: "ZNormalization"

      - name: "ToTensor"

    val:  # Transforms for validation set
      - name: "MRITorchIOPipeline"
        params:
          transforms_config:
            - name: "Resize"
              params:
                target_shape: *target_size

            - name: "ZNormalization"

      - name: "ToTensor"

    test:  # Transforms for test set
      - name: "MRITorchIOPipeline"
        params:
          transforms_config:
            - name: "Resize"
              params:
                target_shape: *target_size

            - name: "ZNormalization"

      - name: "ToTensor"

dataloader:
  global_batch_size: &global_batch_size 2
  train:
    batch_size: *global_batch_size
    shuffle: true
    num_workers: 4
    pin_memory: true

  val:
    batch_size: *global_batch_size
    shuffle: false
    num_workers: 4
    pin_memory: true

  test:
    batch_size: *global_batch_size
    shuffle: false
    num_workers: 4
    pin_memory: true
