name: BMRI_baseline
hidden_size: 128

# Additional model parameters can be added here
architecture:
  type: "3D-CNN"
  input_channels: 1
  output_classes: 4  # Number of molecular subtypes
  layers:
    - type: "conv3d"
      filters: 32
      kernel_size: [3, 3, 3]
      activation: "relu"
    - type: "maxpool3d"
      pool_size: [2, 2, 2]
    - type: "dropout"
      rate: 0.25
