training:
  optimizer:
    name: "Adam"
    params:
      lr: 0.0001
      betas: [0.9, 0.999]
      eps: 1e-8
      amsgrad: False
      weight_decay: 0.0001

  scheduler:
    name: "reduce_on_plateau"
    params:
      mode: "min"
      factor: 0.1
      patience: 10
      min_lr: 1e-6

  loss:
    name: "focal_loss"
    params:
      alpha: 0.25
      gamma: 2.0
      reduction: "mean"

  grad_clip:
    enabled: true
    type: "norm"
    value: 1.0

  metrics:
    - accuracy
    - f1_score
    - auc
